### ISSUE TITLE
update readme  – slurmel_allocate doesn't exist

### ISSUE THREAD

**Issue by bjudkewitz** [FZJ-JSC/jupyter-slurm-provisioner#1]
https://github.com/FZJ-JSC/jupyter-slurm-provisioner/blob/f77f54482ca372b66db687a93e8c69b80a8d9752/README.md?plain=1#L7

> You may have to update `scripts/slurmel_allocate`

This script doesn't exist. I assume this should refer to `SlurmProvisioner.slurm_allocate`, correct?

**Comment by jhgoebbert** [comment]
Yes, the script moved to the function `slurm_allocate` here 
https://github.com/FZJ-JSC/jupyter-slurm-provisioner/blob/main/jupyter_slurm_provisioner/provisioner.py#L441
